Flavie\MovieBundle\Entity\Actor:
    type: entity
    table: null
    repositoryClass: Flavie\MovieBundle\Repository\ActorRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

    lifecycleCallbacks: {  }
